//
//  StudentLocation.swift
//  OnTheMap
//
//  Created by Kenneth Gutierrez on 5/12/22.
//

import Foundation

struct StudentInformation: Codable {
    
    //a StudentInformation struct to store individual locations and links downloaded from the web service:
    struct StudentsData: Codable {
        // the date when the student location was created:
        let createdAt: String?
        // the first name of the student which matches their Udacity profile first name OR an anonymized name hardcoded in your app (see above)::
        let firstName: String
        // the last name of the student which matches their Udacity profile last name OR an anonymized name hardcoded in your app (see above):
        let lastName: String
        // the latitude of the student location (ranges from -90 to 90)
        let latitude: Double
        // the longitude of the student location (ranges from -180 to 180):
        let longitude: Double
        // the location string used for geocoding the student location:
        let mapString: String
        // the URL provided by the student:
        let mediaURL: String
        // an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation:
        let objectId: String?
        // an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id:
        let uniqueKey: String
        // the date when the student location was last updated:
        let updatedAt: String?
        
    }
    
    let results: [StudentsData]
    
}
